### PR TITLE
Convert `is_authenticated`, `is_active`, and `is_anonymous` to properties to conform with Flask-Login >=0.3.0

### PR DESCRIPTION
**Pull request by 01walid**
`@groups_required` decorator no longer works after upgrading `stormpath-flask` to the latest release because of this..

### CODE REVIEW

**Comment by jcass77** [comment]
Seems like an obvious fix - can we have this merged in?

**Comment by rdegges** [comment]
Thanks everyone!

**Comment by 01walid** [comment]
You're welcome,
It'd be cool if you can issue a pypi release :)

**Comment by rdegges** [comment]
I'll get this out later today =) and will drop a comment here

**Comment by rdegges** [comment]
This got released late last night. Forgot to update the ticket, but it is out now.

**Pull request merged**
