### PR TITLE
Add error for facebook

### PR DESCRIPTION
**Pull request by gtmanfred**
But allow others to be able to use stormpath with python3

### CODE REVIEW

**Comment by gtmanfred** [comment]
should allow for most things to run in python3 for #26, except for Facebook obviously :+1:

**Comment by bnaul** [comment]
Would it be possible to merge and release this rather than waiting on Facebook's next release? Seems like a sensible way to get Python3 to be (mostly) supported, and it doesn't seem like `facebook-sdk` is exactly a top priority over there...

**Comment by avojnovicDk** [comment]
:+1:

**Comment by rdegges** [comment]
Thank you for the contribution =)

**Pull request merged**
