### PR TITLE
Update views.py

### PR DESCRIPTION
**Pull request by cpi-zachary-cassity**

### CODE REVIEW

**Comment by rdegges** [comment]
Thanks!

**Comment by jcass77** [comment]
This should probably go into the 'develop' branch as well?

**Comment by rdegges** [comment]
No -- we're currently using the develop branch for the new release of this library which has feature parity with our core API ;O

**Comment by rdegges** [comment]
Sorry, I misspoke. You are correct. The work I was referring to is in a feature branch, sorry!

**Pull request merged**
